name: lps25
channels:
  - conda-forge
dependencies:
  - python
  - matplotlib>=3.10.3,<4
  - geopandas>=1.1.0,<2
  - dask>=2025.5.1,<2026
  - netcdf4>=1.7.2,<2
  - zarr>=3.0.8,<4
  - fsspec>=2025.5.1,<2026
  - pooch>=1.8.2,<2
  - jupyter>=1.1.1,<2
  - rioxarray>=0.19.0
  - joblib>=1.5.1,<2
  - cfgrib>=0.9.15.0,<0.10
  - contextily>=1.6.2,<2
  - pip
  - pip:
      - exactextract
      - xvec
      - cf-xarray
